The import should be "wangeditor" instead of "wangEditor"
error when starting dev server:
```
Error: The following dependencies are imported but could not be resolved:

  wangEditor (imported by /home/zfn/vue-manage-system/src/views/Editor.vue)

Are they installed?
```